### ISSUE TITLE
Tabs not scrolled on init on support library 23.3.0

### ISSUE THREAD

**Issue by gregacucnik** [nshmura/RecyclerTabLayout#14]
If you set current pager item that is outside TabLayout (selectedView == null), tabs dont scroll to that item position. This happens when using 23.3.0 support library and only at view initialization. Once you move pager, tabs jump to the correct position.

Support Library 23.3.0 LinearLayoutManager has a new feature called setAutoMeasureEnabled which is default enabled. This seems to cause this issue on init.

The solution is to set it to false in the RecyclerTabLayout constructor when setting LinearLayoutManager.

``` java
       /.../
        mIndicatorPaint = new Paint();
        mLinearLayoutManager = new LinearLayoutManager(getContext());
        mLinearLayoutManager.setOrientation(LinearLayoutManager.HORIZONTAL);
        mLinearLayoutManager.setAutoMeasureEnabled(false);
        setLayoutManager(mLinearLayoutManager);
        setItemAnimator(null);
        /.../
```

**Comment by nshmura** [comment]
Hi @gregacucnik ,
Thank you for your reporting!
I'll check this issue, please wait.

**Comment by nshmura** [comment]
@gregacucnik 
Sadly enough, I can't reproduce this bug.
Would you please tell me the program that reproduces this bug?

**Comment by gregacucnik** [comment]
This occurs on Nexus 5 running Marshmallow 6.0.1 (and 6.0). I tried old Samsung S3 with 4.3 and it works correctly.

In Activity onCreate i set RecyclerTabLayout with custom adapter and current item is in the middle of all possible items (51 items, the middle one is 25).

**Comment by nshmura** [comment]
@gregacucnik Sorry for late response. I still can't reproduce this bug.
Is it possible that you show the source code ?

**Comment by gregacucnik** [comment]
I cant send you the source code because its part of a massive project.
Im trying to alter your demo to get the bug to occur but i also cant do it. 

I can give your more directions:
- im using Fragments with an custom FragmentStatePagerAdapter
- i use setupWithAdapter method
- after everything is initialized i set current item to the middle (something like your demo Years)
- Tab Layout scroll is disabled
- In the onCreateViewHolder i alter each item width in order to set have specific number of items visible in the Tab Layout

I found that the problem is in the onCreateViewHolder where i change the item width. If i remove this code Tab Layout is scrolled correctly (setAutoMeasureEnabled is also removed). However it doesnt happen in your demo.

Here is the approximate code:

```java
 @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.layout_custom_view01_tab, parent, false);

        ViewGroup.LayoutParams layoutParams = view.getLayoutParams();
        layoutParams.width = parent.getWidth() / 3;

        view.setLayoutParams(layoutParams);

        return new ViewHolder(view);
    }
```

Currently, I dont have time to investigate why this happens. It seems that is has something to do with measuring layout (maybe also connected with fragments).

**Comment by nshmura** [comment]
@gregacucnik Thank you for your detailed information!

**Comment by nshmura** [comment]
I can't reproduce with support library 26.0.1 on Nexus 5 running Marshmallow 6.0.1.

If you have had this issue yet, please open this issue again.
