### ISSUE TITLE
Was there any possible load image Picasso or Glide Recycler Tablayout ?

### ISSUE THREAD

**Issue by araurangel** [nshmura/RecyclerTabLayout#17]
I have following the example of customview01 by using the this DemoCustomView01Activity.class
then in adapter DemoCustomView01Adapter which I used picasso to load image by 
Picasso.with(context).load(item.getUrl()).into(holder.image); I think will load image into imageview.
But the result it was not..anybody can help me about this one please

**Comment by nshmura** [comment]
Hi @araurangel 
Please refer https://github.com/nshmura/RecyclerTabLayout/commit/a72e38c20a4116f2d3fc2eac22a2248369062eea

<img src="https://cloud.githubusercontent.com/assets/9046837/15092559/81bdbc78-14a8-11e6-8536-0db5eb2d6be9.png" width="50%">

**Comment by araurangel** [comment]
@nshmura it work like a charm...I'm really appreciated that..thanks

**Comment by nshmura** [comment]
@araurangel 😄
