### ISSUE TITLE
requestLayout() improperly called

### ISSUE THREAD

**Issue by HashirLabs** [nshmura/RecyclerTabLayout#20]
I am getting this warning , may be you want to look at it

W/View: requestLayout() improperly called by com.nshmura.recyclertablayout.RecyclerTabLayout{10a88d34 VFED.... ......ID 30,0-1050,144 #7f0e0093 app:id/recycler_tab_layout} during layout: running second layout pass

Android SDK : 24.0.1

**Comment by nshmura** [comment]
@HashirLabs Thank you for your reporting! I will check this warning.

**Comment by nshmura** [comment]
This problem was improved by https://github.com/nshmura/RecyclerTabLayout/pull/30 .
