### ISSUE TITLE
Selected tab color not applicable

### ISSUE THREAD

**Issue by mishindmitriy** [nshmura/RecyclerTabLayout#21]
i set color from xml: rtl_tabSelectedTextColor="@android:color/white", but selected tab color always is black

**Comment by mishindmitriy** [comment]
sorry, "app:" prefix resolved my problem

**Comment by nshmura** [comment]
@mishindmitriy Thanks for your reporting 👍 I see!

**Comment by mishindmitriy** [comment]
@nshmura Thanks for your library, its very good

**Comment by nshmura** [comment]
:blush:
