### ISSUE TITLE
Lag when switching from last tab

### ISSUE THREAD

**Issue by JelleBlaauw** [nshmura/RecyclerTabLayout#23]
I currently use the loop method to infinitely scroll through tabs. It all works fine when I switch between fragments when swiping the viewpager itself, however, when I switch from **the last to the first tab** _or_ **the last to the previous tab** by clicking on the tabs in the RecyclerTabLayout, some lag occurs.

**Comment by nshmura** [comment]
Sorry for late response. I can't reproduce this issue. 
Will you send me your os version ?
And please reopen this issue if you need.
