### ISSUE TITLE
4.4.4color invalid

### ISSUE THREAD

**Issue by wuyifengWYF** [nshmura/RecyclerTabLayout#26]
On the android4.4.4 system, the default font color set on the style file is invalid

**Comment by wuyifengWYF** [comment]
If the 4.4.4 color fails, you can set up Android: textcolorsecondary =" color" directly in the XML file

**Comment by nshmura** [comment]
@wuyifengWYF Sorry for late response. Could you please send the screen shot? I am not sure what happen on your android 4.4.4 system.

**Comment by wuyifengWYF** [comment]
It is that every XML file in demo introduces a background style, and the introduced style has an Android: textcolorsecondary =" color" attribute, and you remember? There is no problem in android5.0 system, but 4. 4. 4system  wrong.  I remember the solution is not to introduce that background,Only write in XML("android : textcolorsecondary =" # XXXXXX ") ok. I think it may be 4. 4. introduction style.

**Comment by nshmura** [comment]
Sorry for late response again. Please open this issue if you need.
