### ISSUE TITLE
tab多行

### ISSUE THREAD

**Issue by wuh876** [nshmura/RecyclerTabLayout#29]
tab多行文本，怎么设置，字体大小不一样

**Comment by nshmura** [comment]
Do you want to know how to change the font size for each tab?
If so, please refer to [DemoCustomView01Activity.java](https://github.com/nshmura/RecyclerTabLayout/tree/master/demo/src/main/java/com/nshmura/recyclertablayout/demo/customview01):

**Comment by wuh876** [comment]
比如两行字，第一行和第二行字体大小不一样

**Comment by nshmura** [comment]
I recommend you to use CustomView and put two textView in it. Then set different font size.

**Comment by wuh876** [comment]
改了一下demo可以实现，多谢

**Comment by nshmura** [comment]
Good luck 👍

**Comment by wuh876** [comment]
recycleview滑到中间的话，以后位置都在中间了，怎么改位置

**Comment by nshmura** [comment]
Can you show me picture or figure that explain what you want.
