### ISSUE TITLE
Swipe left not change title color, version 1.4.0

### ISSUE THREAD

**Issue by mishindmitriy** [nshmura/RecyclerTabLayout#33]
Hi, see bug in video: https://www.dropbox.com/s/jrl7ttava4hr5l0/recyclertablayout_bug.mp4?dl=0
version 1.1.0 not have this bug

**Comment by nshmura** [comment]
@mishindmitriy 
Thank you for your report!

Oh I missed.  Will you please try `v1.5.0`?

**Comment by orhunkupeli7** [comment]
In 1.5.0 it doesn't center the selected title at the beginning. After a swipe it turns normal and centers the selected title.

**Comment by nshmura** [comment]
@orhunkupeli7 
I can't reproduce your issue.
Could you show me your screenshot?

And I change a little, please check version `1.5.1.snapshot`.
( https://github.com/nshmura/RecyclerTabLayout/commit/93e27fa1d887902fe2b117fef0223ce54eda7459 )

**Comment by orhunkupeli** [comment]
![recyclertab](https://user-images.githubusercontent.com/26766101/29777313-4661b834-8c14-11e7-87c2-c78a2cc9c88a.PNG)

At the beginning it looks like this after a swipe it centers the selected one. Thanks for your reply. 1.5.1.snapshot is same by the way.

**Comment by nshmura** [comment]
Thanks for your snapshot!
It's odd ...

If it is possible, Would you please show me your code or sample code it reproduce this issue ?

Or please try "ImitationLoop" in demo application,  and tell me what happened.
https://github.com/nshmura/RecyclerTabLayout/tree/master/demo

And Would you please tell me your device and OS version?

**Comment by nshmura** [comment]
@orhunkupeli 
Thanks for your snapshot!
It's odd ...

If it is possible, Would you please show me your code or sample code that reproduces this issue ?

Or please try "ImitationLoop" in demo application, and tell me what happened.
https://github.com/nshmura/RecyclerTabLayout/tree/master/demo

And Would you please tell me your device and OS version?

**Comment by mishindmitriy** [comment]
@nshmura 1.5.1 works good, thank you!
