### ISSUE TITLE
Text Size

### ISSUE THREAD

**Issue by zulfuadar** [nshmura/RecyclerTabLayout#37]
Hi. I have tried to change text size of each tab. How can I chance it?.

Here my code. I thought I can set it through "tabTextAppearance". But it did not affect :(

 android:id="@+id/home_screen_recycler_tab_layout"
                android:layout_width="match_parent"
                android:layout_height="50dp"
                android:background="@color/engly_light_purple"
                app:rtl_tabIndicatorColor="@color/subtitle_dark_purple"
                app:rtl_tabIndicatorHeight="50dp"
                app:rtl_tabSelectedTextColor="@color/white"
                app:rtl_tabTextAppearance="@dimen/home_screen_home_catagories"

**Comment by nshmura** [comment]
@zulfuadar Hi, 
Try like below.

Add style like this:
```
<style name="MyTextAppearanceSmall" parent="@android:style/TextAppearance.Small">  
     <item name="android:textSize">14dp</item>  
</style>
```

And set it like this:
```
<com.nshmura.recyclertablayout.RecyclerTabLayout
        ...
        rtl_tabTextAppearance="@style/MyTextAppearanceSmall"/>
```
