### ISSUE TITLE
How to set the item with same width

### ISSUE THREAD

**Issue by hush881025** [nshmura/RecyclerTabLayout#4]
Excuse me,If i want to set the tab item with same width ,how to solve it ?

**Comment by hush881025** [comment]
and not allowed to scroll

**Comment by nshmura** [comment]
Hi @hush881025 

> set the tab item with same width 

Please try below code.
```
<com.nshmura.recyclertablayout.RecyclerTabLayout
        ....
        rtl_tabMinWidth="100dp"
        rtl_tabMaxWidth="100dp"/>
```

> and not allowed to scroll

Sorry, there is no support for diallow scrolling.
Something like this might work:
```
public class NoScrollTabLayout extends RecyclerTabLayout {

    public NoScrollTabLayout(Context context){
        super(context);
    }

    public NoScrollTabLayout(Context context, AttributeSet attrs){
        super(context, attrs);
    }

    public NoScrollTabLayout(Context context, AttributeSet attrs, int style){
        super(context, attrs, style);
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev){
        if(ev.getAction() == MotionEvent.ACTION_MOVE) {
            return true;
        }
        return super.dispatchTouchEvent(ev);
    }
}
````

see
http://stackoverflow.com/questions/30222310/disable-scrolling-in-child-recyclerview-android

**Comment by hush881025** [comment]
thanks

**Comment by hush881025** [comment]
but,If i want to set three tab to the RecyclerTabLayout,how to set the width just equal the screen width

**Comment by nshmura** [comment]
Currently RecyclerTabLayout do not have options for fill screen width.

`android.support.design.widget.TabLayout` has such options.

```
<android.support.design.widget.TabLayout
        ....
        app:tabMode="fixed"
        app:tabGravity="fill"/>
```

Please use TabLayout for such case.

**Comment by mori-honest** [comment]
I need this too, I think it would be nice to implement this.

**Comment by nshmura** [comment]
@hush881025 @mori-honest Sorry for very late implementation. `rtl_tabOnScreenLimit` attribute was added on version `1.0.0`.
