### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by DJafari** [nshmura/RecyclerTabLayout#5]
hi, thanks for your great library

can you add rtl support to this library ?

everything is ok, but Indicator moves reverse .

**Comment by nshmura** [comment]
hi, thank you for your suggestion.

I made sample of RTL support by application.
Please refer to this commit.
https://github.com/nshmura/RecyclerTabLayout/pull/6/files

Since ViewPager is not support RTL, I think that suporting RTL by RecyclerTabLayout is difficult.

**Comment by nshmura** [comment]
@DJafari Sorry for late reply.
RecyclerTabLayout now support RTL layout.

1. add `android:supportsRtl="true"` attribute to AndroidManifest.xml
```
    <application
            ...
            android:supportsRtl="true">
```

2.  add `android:layoutDirection="rtl"` to layout.xml
```
<RelativeLayout
    ...
    android:layoutDirection="rtl">
```
