### ISSUE TITLE
Slide the time, how to make the indicator is not always in the middle，Similar messenger stickers

### ISSUE THREAD

**Issue by xiang-jian** [nshmura/RecyclerTabLayout#7]

**Comment by nshmura** [comment]
Hi @xiang-jian 
Sorry, RecyclerTabLayout does not have that option.

**Comment by jdpxiaoming** [comment]
自己实现下,思路就是滑动停止再去监听,但是我觉得那样很丑不实时

**Comment by nshmura** [comment]
Hi @jdpxiaoming
If the issue is different, please make new issue.
And please comment in english.
